# Generated by Django 4.1.4 on 2022-12-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_alter_teacher_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacher')),
            ],
        ),
    ]
