# Generated by Django 4.1.4 on 2022-12-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0005_teachercredentials_status_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercredentials',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_credentials', to='Teachers.teacher'),
        ),
    ]
