# Generated by Django 4.1.4 on 2022-12-27 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teachers', '0007_alter_teachercredentials_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercredentials',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
