# Generated by Django 4.1.4 on 2022-12-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0009_teachercredentials_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercredentials',
            name='certificate',
            field=models.ImageField(upload_to=''),
        ),
    ]
