# Generated by Django 4.1.4 on 2022-12-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0010_alter_teachercredentials_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
    ]
