# Generated by Django 4.1.4 on 2022-12-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0011_remove_teacher_date_of_birth_remove_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
