# Generated by Django 4.1.4 on 2022-12-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0012_teacher_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercredentials',
            name='profile_picture',
        ),
    ]
