# Generated by Django 4.1.4 on 2023-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0002_alter_subjects_options'),
        ('Teachers', '0015_teacher_certificate_delete_teachercredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='courseformat.subjects'),
        ),
    ]
