# Generated by Django 4.1.4 on 2023-01-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0002_alter_subjects_options'),
        ('Teachers', '0016_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, to='courseformat.subjects'),
        ),
    ]
