# Generated by Django 4.1.4 on 2023-01-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0017_alter_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
