# Generated by Django 4.1.4 on 2023-01-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0003_remove_subjects_id_alter_subjects_title'),
        ('Teachers', '0018_remove_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(blank=True, to='courseformat.subjects'),
        ),
    ]
