# Generated by Django 4.1.4 on 2022-12-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
