# Generated by Django 4.1.4 on 2022-12-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_student_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
