# Generated by Django 4.1.4 on 2022-12-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_remove_student_date_of_birth_remove_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
