# Generated by Django 4.1.4 on 2023-01-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_alter_student_profile_image_alter_student_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('8th grade', '8th grade'), ('9th grade', '9th grade'), ('10th grade', '10th grade'), ('11th grade', '11th grade'), ('12th grade', '12th grade')], max_length=15),
        ),
    ]
