# Generated by Django 4.1.4 on 2023-01-18 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0015_chaptermaterials_file_type'),
        ('Students', '0007_alter_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseJoined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseformat.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
            ],
        ),
    ]
