# Generated by Django 4.1.4 on 2023-01-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_student_sstudentuniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursejoined',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_student_course', to='Students.student'),
        ),
    ]
