# Generated by Django 4.1.4 on 2022-12-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
