# Generated by Django 4.1.4 on 2022-12-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0003_account_verified_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], default='S', max_length=1),
        ),
    ]
