# Generated by Django 4.1.4 on 2022-12-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0007_account_date_of_birth_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
