# Generated by Django 4.1.4 on 2022-12-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0009_rename_verified_teacher_account_verified_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametest', models.CharField(max_length=255)),
            ],
        ),
    ]
