# Generated by Django 4.1.4 on 2022-12-29 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0010_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='user_id',
            field=models.ForeignKey(default= 2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
