# Generated by Django 4.1.4 on 2022-12-29 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0011_teste_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='agetest',
            field=models.CharField(default='ww', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teste',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testerrr', to=settings.AUTH_USER_MODEL),
        ),
    ]
