# Generated by Django 4.1.4 on 2022-12-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0012_teste_agetest_alter_teste_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
