# Generated by Django 4.1.4 on 2023-01-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0013_alter_account_date_of_birth_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.CharField(blank=True, choices=[('A', 'Admin'), ('S', 'Student'), ('T', 'Teacher')], max_length=1, null=True),
        ),
    ]
