# Generated by Django 4.1.4 on 2023-01-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0014_alter_account_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='verified_role',
            new_name='verified_student',
        ),
        migrations.AddField(
            model_name='account',
            name='verified_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
