# Generated by Django 4.1.4 on 2023-01-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0016_rename_verified_student_account_verified_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='data_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
