# Generated by Django 4.1.4 on 2022-12-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects'},
        ),
    ]
