# Generated by Django 4.1.4 on 2023-01-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0002_alter_subjects_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='id',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
