# Generated by Django 4.1.4 on 2023-01-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0004_coursematerial_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
