# Generated by Django 4.1.4 on 2023-01-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0006_course_grade_coursematerial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
    ]
