# Generated by Django 4.1.4 on 2023-01-09 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0007_remove_course_title_delete_coursematerial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
                ('chapter_description', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseformat.course')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseformat.chapters')),
            ],
        ),
    ]
