# Generated by Django 4.1.4 on 2023-01-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0008_chapters_chaptermaterials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptermaterials',
            options={'verbose_name_plural': 'Chapter material'},
        ),
        migrations.AlterModelOptions(
            name='chapters',
            options={'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Course'},
        ),
    ]
