# Generated by Django 4.1.4 on 2023-01-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0009_alter_chaptermaterials_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermaterials',
            name='chapter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_materials', to='courseformat.chapters'),
        ),
    ]
