# Generated by Django 4.1.4 on 2023-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0010_alter_chaptermaterials_chapter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermaterials',
            name='file_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chaptermaterials',
            name='file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
