# Generated by Django 4.1.4 on 2023-01-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0013_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
