# Generated by Django 4.1.4 on 2023-01-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0014_chapters_slug_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermaterials',
            name='file_type',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
