# Generated by Django 4.1.4 on 2023-01-25 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseformat', '0016_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermaterials',
            name='user_id',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
