# Generated by Django 4.1.4 on 2023-01-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseformat', '0018_chapters_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
